### ISSUE TITLE
项目跑不起来， 显示 错误:程序包androidx.annotation不存在

### ISSUE THREAD

**Issue by AnnaSearl** [Jayruiping/FastEC#4]
![image](https://user-images.githubusercontent.com/26404546/108457470-a8183700-72ad-11eb-8ce2-b69bff913cf8.png)

**Comment by zion223** [comment]
附一下Build 窗口的内容

**Comment by AnnaSearl** [comment]
@zion223 

![image](https://user-images.githubusercontent.com/26404546/108463372-3f36bc00-72b9-11eb-9bb8-ec62fbbc638c.png)

**Comment by zion223** [comment]
百度下看看怎么解决吧，我没遇到过这个问题。
